services:
  mongodb:
    image: mongo:7.0
    container_name: warning_system_mongodb
    restart: unless-stopped
    network_mode: host
    environment:
      MONGO_INITDB_DATABASE: landslide_monitor
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: logm250/warning_system_backend:dev
    container_name: warning_system_backend
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - MONGODB_URI=mongodb://localhost:27017/
      - MONGODB_DB=landslide_monitor
      - HOST=0.0.0.0
      - COAP_PORT=5683
      - HTTP_PORT=3000
      - ENVIRONMENT=production
      - LOG_LEVEL=DEBUG
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/home/appuser/warning_system/logs

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local